services:
  - type: web
    name: lexora-live
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: "False"
      - key: SESSION_COOKIE_SAMESITE
        value: "None"
      - key: APP_URL
        value: https://lexora-live.onrender.com
